// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apief;

#nullable disable

namespace V2iSafe.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241005100312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Dbo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apief.AdditionalField", b =>
                {
                    b.Property<Guid>("passwordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("additionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("passwordId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("passwordId");

                    b.HasIndex("passwordId1");

                    b.ToTable("AdditionalFields", "Dbo");
                });

            modelBuilder.Entity("apief.Note", b =>
                {
                    b.Property<Guid?>("noteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("lastEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noteId");

                    b.ToTable("Note", "Dbo");
                });

            modelBuilder.Entity("apief.Password", b =>
                {
                    b.Property<Guid?>("passwordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("lastEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("passwordId");

                    b.ToTable("Password", "Dbo");
                });

            modelBuilder.Entity("apief.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User", "Dbo");
                });

            modelBuilder.Entity("apief.AdditionalField", b =>
                {
                    b.HasOne("apief.Password", "Password")
                        .WithMany("additionalFields")
                        .HasForeignKey("passwordId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Password");
                });

            modelBuilder.Entity("apief.Password", b =>
                {
                    b.Navigation("additionalFields");
                });
#pragma warning restore 612, 618
        }
    }
}
